const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Car,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.gamepad,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.progressbar,
		C3.Behaviors.Pin,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.gamepad.Cnds.OnButtonUp,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Behaviors.Car.Acts.SimulateControl,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.progressbar.Acts.SetInstanceVar,
		C3.Plugins.progressbar.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Car.Acts.SetAcceleration,
		C3.Behaviors.Car.Acts.SetMaxSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.progressbar.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.progressbar.Cnds.CompareInstanceVar,
		C3.Plugins.progressbar.Exps.Maximum,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.System.Exps.dt,
		C3.JavaScriptInEvents.Events_sea_Event26_Act1,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor
	];
};
self.C3_JsPropNameTable = [
	{car_accelerationBase: 0},
	{car_maxSpeedValue0: 0},
	{car_maxSpeedValue1: 0},
	{car_maxSpeedValue2: 0},
	{car_accelerationBoost: 0},
	{car_ControlReadyForBoost: 0},
	{car_anchorIsUp: 0},
	{Car: 0},
	{ScrollTo: 0},
	{Solid: 0},
	{Logic_Boat: 0},
	{Logic_Keyboard: 0},
	{Map_Rock: 0},
	{Logic_Gamepad: 0},
	{uiText_timer: 0},
	{Anchor: 0},
	{GUI_BoostText: 0},
	{ProgressBar_currentValue: 0},
	{GUI_ProgressBar: 0},
	{Pin: 0},
	{GUI_AnchorIcon: 0},
	{WindDirection_CurrentAngleValue: 0},
	{WindDirection_TargetAngleValue: 0},
	{WindDirection_CountdownDirectionChange: 0},
	{WindDirection_CurrentValueTween: 0},
	{Tween: 0},
	{GUI_WindDirection: 0},
	{SailDirection_RotationSpeed: 0},
	{Wind_WindAngleThresholdGood: 0},
	{Wind_WindAngleThresholdPerfect: 0},
	{Wind_CurrentThreshold: 0},
	{Wind_WindThresholdMultiplierPerfect: 0},
	{Wind_WindThresholdMultiplierGood: 0},
	{Wind_WindThresholdMultiplierBad: 0},
	{Wind_CurrentBoostBarMultiplier: 0},
	{GUI_SailDirection: 0},
	{GUI_Console: 0}
];

self.InstanceType = {
	Logic_Boat: class extends self.ISpriteInstance {},
	Logic_Keyboard: class extends self.IInstance {},
	Map_Rock: class extends self.ISpriteInstance {},
	Logic_Gamepad: class extends self.IInstance {},
	GUI_BoostText: class extends self.ITextInstance {},
	GUI_ProgressBar: class extends self.IProgressBarInstance {},
	GUI_AnchorIcon: class extends self.ISpriteInstance {},
	GUI_WindDirection: class extends self.ISpriteInstance {},
	GUI_SailDirection: class extends self.ISpriteInstance {},
	GUI_Console: class extends self.ITextInstance {}
}