const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Car,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Tween,
		C3.Plugins.Keyboard,
		C3.Plugins.gamepad,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.progressbar,
		C3.Behaviors.Pin,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.gamepad.Cnds.OnGamepadConnected,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.gamepad.Exps.GamepadIndex,
		C3.Plugins.gamepad.Cnds.OnAnyButtonDown,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Car.Acts.Stop,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Behaviors.Car.Acts.SimulateControl,
		C3.Behaviors.Car.Acts.SetMaxSpeed,
		C3.Behaviors.Car.Acts.SetAcceleration,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.gamepad.Cnds.OnButtonUp,
		C3.Plugins.gamepad.Acts.ResetVibrate,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.gamepad.Acts.VibrateTriggerRumble,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.dt,
		C3.JavaScriptInEvents.Events_sea_Event36_Act1,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Acts.SetInstanceVar,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{acceleration_rows: 0},
	{maxSpeed_Rows: 0},
	{maxSpeed_sails: 0},
	{acceleration_sails: 0},
	{ControlMode: 0},
	{Rows_Active: 0},
	{Rows_Operating: 0},
	{maxSpeed_sailsBoost: 0},
	{acceleration_sailsBoost: 0},
	{Car: 0},
	{ScrollTo: 0},
	{Solid: 0},
	{Tween: 0},
	{Logic_Boat: 0},
	{Logic_Keyboard: 0},
	{Map_Rock: 0},
	{Logic_Gamepad: 0},
	{uiText_timer: 0},
	{Anchor: 0},
	{GUI_BoostText: 0},
	{ProgressBar_currentValue: 0},
	{GUI_ProgressBar: 0},
	{Active: 0},
	{Pin: 0},
	{GUI_AnchorIcon: 0},
	{WindDirection_CurrentAngleValue: 0},
	{WindDirection_TargetAngleValue: 0},
	{WindDirection_CountdownDirectionChange: 0},
	{WindDirection_CurrentValueTween: 0},
	{GUI_WindDirection: 0},
	{Operating: 0},
	{boatAngle_state: 0},
	{GUI_SailDirection: 0},
	{GUI_Console: 0},
	{PlayerInputText: 0},
	{mainM_TextInput: 0},
	{mainM_Button: 0},
	{mainM_Text: 0},
	{mainM_ButtonRumble: 0},
	{mainM_TextRumble: 0},
	{mainM_TextRumbleStatus: 0},
	{Text: 0},
	{RumbleActive: 0},
	{ActiveGamepadIndex: 0},
	{Password: 0}
];

self.InstanceType = {
	Logic_Boat: class extends self.ISpriteInstance {},
	Logic_Keyboard: class extends self.IInstance {},
	Map_Rock: class extends self.ISpriteInstance {},
	Logic_Gamepad: class extends self.IInstance {},
	GUI_BoostText: class extends self.ITextInstance {},
	GUI_ProgressBar: class extends self.IProgressBarInstance {},
	GUI_AnchorIcon: class extends self.ISpriteInstance {},
	GUI_WindDirection: class extends self.ISpriteInstance {},
	GUI_SailDirection: class extends self.ISpriteInstance {},
	GUI_Console: class extends self.ITextInstance {},
	mainM_TextInput: class extends self.ITextInputInstance {},
	mainM_Button: class extends self.IButtonInstance {},
	mainM_Text: class extends self.ITextInstance {},
	mainM_ButtonRumble: class extends self.IButtonInstance {},
	mainM_TextRumble: class extends self.ITextInstance {},
	mainM_TextRumbleStatus: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {}
}